In [1]:
import numpy as np
ar1 = np.arange(10,dtype=float)
print(ar1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [3]:
np.__version__

'1.21.5'

In [5]:
arr = np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
l = [1,2,3,4,5]
l


[1, 2, 3, 4, 5]

In [15]:
l2=[x for x in range(0,10)]
l2



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l3=[str(x) for x in l2]
l3


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [18]:
l4=[x for x in range(0,10,2)]
l4

[0, 2, 4, 6, 8]

In [19]:
l4 = [x**2 for x in range(0,10)]
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [21]:
import array

In [22]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array
    
    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |  
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |  
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined

In [26]:
arr = array.array('i',l2)
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr = array.array('f',l2)
arr

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [29]:
type(arr)

array.array

In [33]:
arr = array.array('i',[x**2 for x in l2])
arr

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [34]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
np.array([x-3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [37]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [38]:
np.array([1,2,3,4],dtype = 'float')

array([1., 2., 3., 4.])

In [39]:
np.array([1,2,3,4],dtype = 'str')

array(['1', '2', '3', '4'], dtype='<U1')

In [40]:
np.array([1,2,3,4],dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [43]:
list = [[1,2,3,4],[4,5,6,7]]
list

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [46]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
lc =[range(i,i+3) for i in [1,3]]
lc

[range(1, 4), range(3, 6)]

In [49]:
np.array(lc)

array([[1, 2, 3],
       [3, 4, 5]])

In [50]:
lc =[range(i,i+3) for i in [1,9]]
lc

[range(1, 4), range(9, 12)]

In [51]:
np.array(lc)

array([[ 1,  2,  3],
       [ 9, 10, 11]])

In [52]:
lc =[range(i,i+3) for i in [1,9,3]]
lc

[range(1, 4), range(9, 12), range(3, 6)]

In [53]:
np.array(lc)

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [ 3,  4,  5]])

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
np.zeros([2,2],dtype = 'int32')

array([[0, 0],
       [0, 0]])

In [57]:
np.zeros([10,10],dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
np.zeros([3,4],dtype = 'int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
arr = np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr[1:9,1:9]= 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
arr[2:8,2:8]=8
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 9., 9., 9., 9., 9., 9., 9., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
arr[3:7,3:7]=7
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 9., 9., 9., 9., 9., 9., 9., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
arr[4:6,4:6]=6
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 9., 9., 9., 9., 9., 9., 9., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 7., 6., 6., 7., 8., 1., 1.],
       [1., 9., 8., 7., 6., 6., 7., 8., 1., 1.],
       [1., 9., 8., 7., 7., 7., 7., 8., 1., 1.],
       [1., 9., 8., 8., 8., 8., 8., 8., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
ar = np.arange(0,9,dtype='float').reshape(3,3)
ar

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [86]:
ar[:] = 3.14
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [90]:
np.full((3,4),'abc')

array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [92]:
#identity matrix
np.eye?

In [93]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [95]:
np.transpose(np.eye(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#list
#list comprehesion
#array modules(imported library array)
#numpy array(zeros,ones,full,eye,arange)
#reshape
#indexing

In [5]:
import numpy as np
a = np.full([6,6],64)
a

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [6]:
#linspace-linearly spaced elements
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.linspace(0,0.1,5)

array([0.   , 0.025, 0.05 , 0.075, 0.1  ])

In [9]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [11]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [13]:
np.random.random((3,3))

array([[0.90059716, 0.69834068, 0.24894002],
       [0.07280642, 0.02985681, 0.37268952],
       [0.79923278, 0.67375921, 0.73879404]])

In [14]:
np.random.random(3)

array([0.14195424, 0.96270378, 0.83692168])

In [15]:
np.random.random((2,3))

array([[0.48779601, 0.06446191, 0.59013172],
       [0.30421978, 0.4374596 , 0.42968404]])

In [19]:
np.random.normal(2,3,size=(3,3))
#values with mean and std 1

array([[-1.12615539,  1.82876908,  4.77940108],
       [ 3.75463686,  3.03553406,  0.99210238],
       [ 0.92137976,  2.24791951,  1.98715561]])

In [24]:
np.random.normal(2,3,size=(10,10))

array([[ 3.65702842,  0.99355866,  0.10978218,  1.83864219, -2.95787056,
         4.93221791,  1.02388055, -1.00434893,  1.27209509,  3.67758215],
       [ 1.57846124,  2.51025685,  2.52354035,  2.2355444 ,  0.21510996,
         2.44853731,  6.37427385, -4.4136362 ,  2.45622452, -0.80810193],
       [-3.91175085,  7.15218869, -0.33641363,  2.82991607, -4.05541663,
         1.97993739,  7.43425007,  1.33075676, -2.65077374, -0.5040048 ],
       [ 5.23460482,  4.69898037, -3.29750236,  3.79206385,  1.87317993,
        -0.80260696, -0.76646774, -0.31746608,  2.59867083,  1.36371048],
       [ 0.06721839, -0.82800531,  2.26320254, -1.49289017,  0.46035191,
         9.01215868, -0.88232599,  1.91678791,  2.85486228, 10.76231121],
       [-6.12941932, -1.83849641,  9.55580671,  3.60487711,  1.21828619,
        -0.22359957, -0.29976425,  4.3247907 ,  1.85072528,  5.12348771],
       [ 2.77166636,  2.81854473,  2.40457532,  9.70564278, -0.73629561,
        -1.88674399,  3.55133486,  2.9415699 

In [28]:
np.random.normal(0,1,(2,2))

array([[ 0.190224  , -0.69775661],
       [-1.80437787,  0.78331257]])

In [31]:
np.random.seed(10)
np.random.random(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [42]:
np.random.seed(7)
np.random.random(5)

array([0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951])

In [48]:
np.random.randint(50,100,36)

array([64, 73, 58, 75, 96, 92, 76, 58, 89, 88, 54, 98, 57, 94, 50, 61, 56,
       69, 94, 55, 74, 98, 50, 84, 59, 64, 88, 54, 96, 59, 73, 85, 53, 58,
       69, 98])

In [50]:
np.random.randn?

In [ ]:
#operation on numpy array


In [55]:
arr = np.random.randint(0,100,(2,2))
arr

array([[75, 58],
       [47, 16]])

In [56]:
arr.ndim # number of dimensions

2

In [57]:
arr.size # number of an element of an array

4

In [58]:
arr.shape

(2, 2)

In [59]:
arr.dtype

dtype('int32')

#array indexing

In [64]:
arr1 = np.random.randint(0,40,10)
arr1

array([ 9, 23, 21,  4, 27, 12, 11,  6, 33, 21])

In [66]:
arr1[4]

27

In [67]:
arr1[-1]

21

In [68]:
arr1[:4]

array([ 9, 23, 21,  4])

In [69]:
arr1[4:]

array([27, 12, 11,  6, 33, 21])

In [70]:
arr1[4:7]

array([27, 12, 11])

In [77]:
arr1[3]=20.25
arr1

array([ 9, 23, 21, 20, 27, 12, 11,  6, 33, 21])

In [40]:
a=np.array([10,20])
a

array([10, 20])

In [120]:
list=[[10,20,20],[40,50,50]]
list
list3=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [113]:
c = np.array(list)
c
c.dtype
c.shape


(2, 3)

In [114]:
d.shape

(3, 2)

In [123]:
d.ndim

2

In [117]:
c.ndim

2

In [118]:
a.ndim

1

In [124]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [130]:
maths=np.random.randint(0,100,20)
maths

array([56, 51, 55, 12, 76, 36, 71, 85, 58, 41, 15, 43, 59, 82, 63, 28, 16,
        5, 35, 77])

In [44]:
import  numpy as np
arr = [1,2,3,4,5,6]
a[2:4:2]

array([], dtype=int32)

In [12]:
arr[::2]

[1, 3, 5]

In [42]:
#reverse
arr[::-1]

[6, 5, 4, 3, 2, 1]

In [16]:
arr[::-2]

[6, 4, 2]

In [21]:
r = np.random.randint(0,10,(4,4))
r

array([[7, 3, 5, 6],
       [1, 4, 1, 1],
       [0, 2, 6, 5],
       [2, 8, 9, 4]])

In [5]:
a=np.arange(0,25).reshape(5,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
a[0,1:4]

array([1, 2, 3])

In [28]:
a[0,1]

1

In [29]:
a[2,1]

11

In [30]:
a[3,3]

18

In [31]:
a[2,4]

14

In [32]:
a[0:3,1]

array([ 1,  6, 11])

In [33]:
a[0:2,1]

array([1, 6])

In [34]:
a[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [37]:
a[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [38]:
a[2:5,3:5]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [41]:
a[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [42]:
a[::,::]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
import numpy as np
a[::-1,::-1]
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
a[2:,3:]


array([[13, 14],
       [18, 19],
       [23, 24]])

In [12]:
a1 = np.ones((10,10))
a1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
a1[1:9,1:9] =0
a1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
a[3:5,3:5]

array([[18, 19],
       [23, 24]])

In [17]:
s = a[3:5,3:5]
s

array([[18, 19],
       [23, 24]])

In [18]:
#shallow copy
s[1,1] = 20
s

array([[18, 19],
       [23, 20]])

In [26]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 16],
       [20, 21, 22, 23, 20]])

In [20]:
a[3,4]

19

In [23]:
y =a[3,4] = 16
y

16

In [24]:
s

array([[18, 16],
       [23, 20]])

In [29]:
#deep copy
s[0:2,0:2]
s

array([[18, 16],
       [23, 20]])

In [45]:
da = a[:2,:2].copy


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [46]:
da[1,1] = 15
da

NameError: name 'da' is not defined

In [37]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [39]:
d =[np.array([1,2,3]).reshape(3,1)]
d

[array([[1],
        [2],
        [3]])]

In [40]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [41]:
e.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [42]:
f = np.arange(0,9)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
f.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
f.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [47]:
f.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
f.ravel?

In [51]:
np.ravel(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.flattened?

Object `np.flattened` not found.


In [55]:
f.flattened?

Object `f.flattened` not found.


In [56]:
f.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
f[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [59]:
#concattenation or joining of two arrays
np.concatenate?

In [66]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])
print(a)
b

[[1 2]
 [3 4]]


array([[5, 6],
       [7, 8]])

In [63]:
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
np.concatenate([a,b],axis = 1) # to specify rows and columns row = 0 and columns = 1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [1]:
import numpy as np


In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
d = np.arange(10,50)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
e = np.arange(10,50,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [13]:
f = np.arange(0,9).reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
g = np.eye(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
h = np.random.random(1)
h

array([0.01960607])

In [16]:
j = np.random.normal(0,30,25)
j

array([ 5.69206894e+01, -4.68548740e+01,  3.03868960e+01,  3.96688366e+01,
       -1.67461176e+01, -3.83278678e+01,  5.26559273e+01, -5.28276403e+00,
       -2.01407154e+01,  1.19961950e+01,  1.60373331e+01,  3.00365317e+01,
       -2.57200426e+01, -3.39872810e+01,  8.73428880e-04,  2.73850796e+00,
       -9.43681908e+00, -7.64519186e+01,  2.02848194e+01,  1.25979632e+01,
        2.42833614e+01, -1.78683550e+01,  3.15323549e+01, -1.61895975e+00,
       -3.00529498e+01])

In [20]:
k = np.linspace(0.01,1,100).reshape(10,10)
k

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [22]:
l = np.linspace(0,1,20)
l

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [35]:
m = np.arange(1,26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
m[2:5,1:5]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [38]:
m[3,4]

20

In [39]:
m[4,0:5]

array([21, 22, 23, 24, 25])

In [40]:
m[3,0:5]

array([16, 17, 18, 19, 20])

In [43]:
total_sum = np.sum(m)
print(total_sum)

325


In [44]:
total_sum = np.sum(m,axis = 0)
print(total_sum)

[55 60 65 70 75]


In [46]:
l = np.std(m)
print(l)

7.211102550927978


In [47]:
m = np.min(m)
print(m)

1


In [48]:
j = np.max(m)
print(j)

1


In [53]:
np.var(m)

0.0

In [54]:
#
np.vstack?

TypeError: Field elements must be 2- or 3-tuples, got '6'

In [58]:
ar = np.array([[1,3],
             [4,5]])
ar

array([[1, 3],
       [4, 5]])

In [59]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [61]:
np.vstack([ar,grid])

NameError: name 'grid' is not defined

In [62]:
np.hstack((ar,[4]))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [63]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

In [65]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [66]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [71]:
ar = np.array([[1,2,3],
              [4,5,6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.vstack([ar,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [82]:
np.split?



In [83]:
np.vsplit?


In [84]:
np.hsplit?

In [85]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [86]:
np.split(a,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

### np.split(a,2)

In [89]:
np.split(a,[2,3])

[array([1, 2]), array([3]), array([4, 5])]

In [90]:
np.split(a,[1,4])

[array([1]), array([2, 3, 4]), array([5])]

In [91]:
np.split(a,[1,2,34])

[array([1]), array([2]), array([3, 4, 5]), array([], dtype=int32)]

In [92]:
a2 = np.arange(0,25).reshape(5,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [94]:
np.hsplit(a2,[2,3])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [96]:
np.vsplit(a2,5)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [97]:
np.abs(-5)

5

In [ ]:
#concatenate
#hstack
#split
#hsplit
#vplit
#aggregation


In [98]:
a

array([1, 2, 3, 4, 5])

In [99]:
np.sum(a)

15

In [100]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.sum(ar)

21

In [102]:
np.sum(ar,axis = 1)

array([ 6, 15])

In [103]:
np.sum(ar,axis = 0)

array([5, 7, 9])

In [104]:
np.min(a)

1

In [105]:
np.max(a)

5

In [106]:
np.min(ar)

1

In [107]:
np.max(ar)

6

In [108]:
np.min(ar,axis = 0)

array([1, 2, 3])

In [109]:
np.max(ar,axis = 1)

array([3, 6])

In [110]:
np.argmin(a)  #index of min 


0

In [111]:
np.argmin(ar)

0

In [112]:
np.argmax(a)

4

In [114]:
a = -5
np.absolute(a)

5

In [115]:
np.std(a)

0.0

In [116]:
np.var(ar)

2.9166666666666665

In [117]:
np.std(ar)

1.707825127659933

In [118]:
np.median(a)

-5.0

In [119]:
np.prod(a)

-5

In [6]:
import numpy as np


In [7]:
np.floor(15/20)

0.0

In [8]:
np.ceil(23/678)

1.0

In [10]:
np.null()

AttributeError: module 'numpy' has no attribute 'null'

In [11]:
np.empty?

In [17]:
a = np.arange(5)
a
b = np.full(5,5)
print(a,b)

[0 1 2 3 4] [5 5 5 5 5]


In [18]:
a + b

array([5, 6, 7, 8, 9])

In [22]:
c= np.full(2,3)[:,np.newaxis]
c

array([[3],
       [3]])

In [23]:
b+c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [33]:
m =np.full(2,3)
n = np.full(2,1) [:,np.newaxis]
s = m + n
print(n)
display(m,n)
display(m + n, s)
display (s + 5)

[[1]
 [1]]


array([3, 3])

array([[1],
       [1]])

array([[4, 4],
       [4, 4]])

array([[4, 4],
       [4, 4]])

array([[9, 9],
       [9, 9]])

In [40]:
o = np.ones((3,3))
a = np.arange(4).reshape(4,1)
display(o,a)
 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[0],
       [1],
       [2],
       [3]])

In [41]:
 
    o + a

ValueError: operands could not be broadcast together with shapes (3,3) (4,1) 

In [ ]:
#broadcasting


NUMPY ASSIGNMENT

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
b = np.arange(10,50,2)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand()

0.9671396667058404

In [28]:
np.random.rand(25)

array([0.51286968, 0.58200296, 0.82342743, 0.55841225, 0.18026585,
       0.17632791, 0.94221047, 0.8626149 , 0.01658639, 0.08345035,
       0.51538317, 0.60273413, 0.28015479, 0.46124653, 0.9258376 ,
       0.33171396, 0.6332984 , 0.11506083, 0.14590693, 0.55795931,
       0.94202792, 0.75110765, 0.6056603 , 0.89645756, 0.36750712])

In [36]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [39]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [5]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [49]:
a[3,4]

20

In [9]:
a[0:3,1:2] 

array([[ 2],
       [ 7],
       [12]])

In [10]:
a[4:]

array([[21, 22, 23, 24, 25]])

In [25]:
a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
np.sum(a)

325

In [52]:
np.sum(a,axis=1)

array([ 15,  40,  65,  90, 115])

In [56]:
np.std(a,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [60]:
np.var(a,axis=0)

array([50., 50., 50., 50., 50.])

In [57]:
np.min(a,axis=0)

array([1, 2, 3, 4, 5])

In [58]:
np.max(a,axis=0)

array([21, 22, 23, 24, 25])

In [61]:
b2 = np.array([10,20,30,40,50,60,70])
b2

array([10, 20, 30, 40, 50, 60, 70])

In [62]:
b2[1:3]

array([20, 30])

In [63]:
b2[1:6:2]

array([20, 40, 60])

In [70]:
b2[-1:-3:-1]

array([70, 60])

In [22]:
import numpy as np

a = np.zeros(20).reshape(4, 5)
a[0, :] = "nan"
a[1:4,0:1] = "nan"
a[3:] = nan
a[1:3,-1:] = np.nan

print(a)


[[nan nan nan nan nan]
 [nan  0.  0.  0. nan]
 [nan  0.  0.  0. nan]
 [nan nan nan nan nan]]


#NUMPY EXERCISE 2

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(a)
print(b)
print(c)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [11]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [14]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 3)
(1, 3, 4)


In [26]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [27]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
Maths_marks = np.random.randint(1,100,20)
Maths_marks

array([81, 41, 51, 93, 13, 72, 24, 25, 99, 93, 39, 94, 66, 49, 25, 19, 67,
       62, 15, 59])

In [37]:
sort_array = np.sort(Maths_marks)
sort_array

array([13, 15, 19, 24, 25, 25, 39, 41, 49, 51, 59, 62, 66, 67, 72, 81, 93,
       93, 94, 99])

In [49]:
sort_array = np.sort(Maths_marks) [::-1]
sort_array

array([90, 87, 84, 84, 83, 81, 76, 58, 58, 42, 37, 33, 29, 27, 27, 23, 20,
       12,  6,  1])

In [51]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
a.reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [55]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)           

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
new_row = np.array([[10,11,12]])

In [60]:
b2 = np.vstack([b,new_row])
print(b2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [73]:
d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
e = d+4
e

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [87]:
g = np.random.rand(10)
g

array([0.88260029, 0.57472813, 0.69905583, 0.0619014 , 0.28883638,
       0.12236267, 0.80766184, 0.90821351, 0.04528249, 0.70954592])

In [90]:
np.ceil(g)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
np.floor(g)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [93]:
np.round(g,decimals=2)

array([0.88, 0.57, 0.7 , 0.06, 0.29, 0.12, 0.81, 0.91, 0.05, 0.71])

In [94]:
h = np.arange(25).reshape(5,5)
h

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
np.min(h,axis = 1)

array([ 0,  5, 10, 15, 20])

In [96]:
np.max(h,axis = 1)

array([ 4,  9, 14, 19, 24])

In [97]:
np.var(h,axis = 1)

array([2., 2., 2., 2., 2.])

In [98]:
np.std(h,axis = 1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [101]:
vect = np.zeros(10)
vect

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [102]:
vect[6] = 200
vect

array([  0.,   0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.])

In [103]:
ar1 = np.arange(100,150)
ar1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [108]:
ar2 = ar1[::-1]
ar2

array([149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111,
       110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [110]:
ar3 = np.arange(0,25).reshape(5,5)
ar3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
b3 = np.array([1,0,2,0,0,4,0,8])
b3

array([1, 0, 2, 0, 0, 4, 0, 8])

In [112]:
np.nonzero(b3)

(array([0, 2, 5, 7], dtype=int64),)

In [10]:
mtr1 = np.zeros((100)).reshape(10,10)
mtr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
mtr1[0:1,0:] = 1
mtr1
mtr1[1:,0:1] = 1
mtr1
mtr1[9:,1:] = 1
mtr1
mtr1[1:9,9:] = 1
mtr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
mtr2 = np.full([8,8],0)
mtr2

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
mtr2[1::2,::2] = 1
mtr2
mtr2[::2,1::2] = 1
mtr2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [25]:
matr1 = np.arange(0,9).reshape(3,3)
print(matr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
matr2 = np.arange(10,19).reshape(3,3)
print(matr2)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [30]:
addition = matr1 + matr2
addition

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [32]:
subtraction = matr1 - matr2
subtraction

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [33]:
multiplication = matr1 * matr2
multiplication

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [34]:
division = matr1 / matr2
division

array([[0.        , 0.09090909, 0.16666667],
       [0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444]])